name: terraform-ec2
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: checkout code
        uses: actions/checkout@v5 # Check out your repo code into the runner

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3 # Install Terraform on the runner

      - name: run init
        run: terraform init # Initialize Terraform in your repo directory

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: run terraform plan
        run: terraform plan

      - name: run terraform apply
        run: terraform apply -auto-approve
